services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc
    restart: unless-stopped

    ports:
      - "25565:25565/tcp"
      - "25575:25575/tcp"
      - "19132:19132/udp"
      - "25563:25563/udp"

    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      PAPER_CHANNEL: "experimental"
      TYPE: "PAPER"
      USE_AIKAR_FLAGS: "true"
      INIT_MEMORY: 350M
      MEMORY: 7250M
      MAX_MEMORY: 7250M

      # Rcon
      ENABLE_RCON: "true"
      RCON_PASSWORD: "CHANGEME"
      RCON_PORT: 25575

      # Plugins (Modrinth gerade Down)
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot

      # Modrinth
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      MODRINTH_PROJECTS: "simple-voice-chat, teaks-tweaks"

      # Server Properties
      SERVER_NAME: "Eumelcraft"
      GAMEMODE: "survival"
      DIFFICULTY: "hard"
      OPS: "Leeeiif"
      WHITELIST: "Leeeiif"
      MAX_PLAYERS: "69"
      MOTD: "Der ECHTE EUMELCRAFT SERVER"
      VIEW_DISTANCE: "12"
      SIMULATION_DISTANCE: "8"
      SYNC_CHUNK_WRITES: "false"
      SPAWN_PROTECTION: "0"
      NETWORK_COMPRESSION_THRESHOLD: 128

      # Auto-Pause Configuration
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: "15"
      AUTOPAUSE_TIMEOUT_INIT: "15"
      #DEBUG_AUTOPAUSE: "false"
      MAX_TICK_TIME: "-1"
      JVM_DD_OPTS: "disable.watchdog:true"

    volumes:
      - /home/leif/minecraft/data:/data

    tty: true
    stdin_open: true

  mc_backup:
    image: itzg/mc-backup
    container_name: mc-backup
    restart: unless-stopped

    depends_on:
      - minecraft

    environment:
      RCON_HOST: mc
      RCON_PASSWORD: "CHANGEME"
      BACKUP_NAME: "eumelcraft_backup"
      BACKUP_INTERVAL: "24h"
      BACKUP_METHOD: "tar"
      BACKUP_RETENTION: "3"
      PRUNE_BACKUPS_DAYS: "7"
      INITIAL_DELAY: "5m"
      BACKUP_ARCHIVE_PERMISSIONS: "0644"
      TZ: "Europe/Berlin"
      BACKUP_UID: "1000"
      BACKUP_GID: "1000"

    volumes:
      - /home/leif/minecraft/data:/data:ro
      - /home/leif/minecraft/backups:/backups
