version: "3.3"
services:
  mc:
    image: itzg/minecraft-server
    ports:
      # Game port
      - 25565:25565/tcp
      - 24454:24454/udp
    environment:
      EULA: "TRUE"
      # server conf
      MOTD: Hallo liebe Eumelcrafter
      DIFFICULTY: HARD
      MAX_PLAYERS: 69
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 8
      SYNC_CHUNK_WRITES: "TRUE"
      NETWORK_COMPRESSION_THRESHOLD: 128
      # Plugins
      MODRINTH_ALLOWED_VERSION_TYPE: ALPHA
      MODRINTH_PROJECTS: teaks-tweaks, leturmemoryrest, simple-voice-chat, viaversion, serverhider
      # AUTO PAUSE
      ENABLE_AUTOPAUSE: "TRUE"
      DEBUG_AUTOPAUSE: "FALSE"
      # Dont Anfassen
      TYPE: PAPER
      FORCE_REDOWNLOAD: "TRUE"
      VERSION: 1.21.3
      SERVER_PORT: 25565
      TZ: Europe/Berlin
      USE_AIKAR_FLAGS: "TRUE"
      INIT_MEMORY: 1G
      MAX_MEMORY: 1G
      MEMORY: 6.5G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: 24h
      RCON_HOST: mc
      PRE_BACKUP_SCRIPT: |
        echo "Before backup!"
        echo "Also before backup from $$RCON_HOST to $$DEST_DIR"
      POST_BACKUP_SCRIPT_FILE: /post-backup.sh
    volumes:
      # mount the same volume used by server, but read-only
      - mc:/data:ro
      - ./mc-backups:/backups
      - ./post-backup.sh:/post-backup.sh:ro
volumes:
  mc: {}
networks: {}
