services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc
    network_mode: "host"
    restart: unless-stopped
    ports:
      # Normal
      - 25565:25565/tcp
      # Rcon
      - 25575:25575/tcp
      # Geyser
      - 19132:19132/udp
      # Voicechat
      - 25563:25563/udp
    environment:
      EULA: "TRUE"
      TZ: ${TIME_ZONE}
      VERSION: ${VERSION}
      PAPER_CHANNEL: experimental
      TYPE: ${SERVER_TYPE}
      USE_AIKAR_FLAGS: "true"
      INIT_MEMORY: 350M
      MEMORY: ${MEMORY}
      MAX_MEMORY: ${MEMORY}
      # Rcon
      ENABLE_RCON: ${ENABLE_RCON}
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: ${RCON_PORT}
      # Modrinth
      MODRINTH_ALLOWED_VERSION_TYPE: ${MODRINTH_ALLOWED_VERSION_TYPE}
      MODRINTH_PROJECTS: ${MODRINTH_PROJECTS}
      # Server Properties
      SERVER_NAME: ${SERVER_NAME}
      GAMEMODE: ${GAMEMODE}
      DIFFICULTY: ${DIFFICULTY}
      OPS: ${OPS}
      WHITELIST: ${WHITELIST}
      MAX_PLAYERS: ${MAX_PLAYERS}
      MOTD: ${MOTD}
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      SIMULATION_DISTANCE: ${SIMULATION_DISTANCE}
      SYNC_CHUNK_WRITES: ${SYNC_CHUNK_WRITES}
      SPAWN_PROTECTION: ${SPAWN_PROTECTION}
      ENFORCE_SECURE_PROFILE: ${ENFORCE_SECURE_PROFILE}
      # Auto-Pause Configuration
      ENABLE_AUTOPAUSE: ${ENABLE_AUTOPAUSE}
      AUTOPAUSE_TIMEOUT_EST: ${AUTOPAUSE_TIMEOUT_EST}
      AUTOPAUSE_TIMEOUT_INIT: ${AUTOPAUSE_TIMEOUT_INIT}
      MAX_TICK_TIME: ${MAX_TICK_TIME}
      JVM_DD_OPTS: ${JVM_DD_OPTS}
    volumes:
      - ${MINECRAFT_DATA}:/data
    tty: true
    stdin_open: true
  mc-backup:
    image: itzg/mc-backup
    container_name: mc-backup
    restart: unless-stopped
    depends_on:
      - minecraft
    environment:
      RCON_HOST: mc
      RCON_PASSWORD: ${RCON_PASSWORD}
      BACKUP_NAME: ${BACKUP_NAME}
      BACKUP_INTERVAL: ${BACKUP_INTERVAL}
      BACKUP_METHOD: ${BACKUP_METHOD}
      BACKUP_RETENTION: ${BACKUP_RETENTION}
      PRUNE_BACKUPS_DAYS: ${PRUNE_BACKUPS_DAYS}
      INITIAL_DELAY: ${INITIAL_DELAY}
      BACKUP_ARCHIVE_PERMISSIONS: "0644"
      TZ: ${TIME_ZONE}
      BACKUP_UID: "1000"
      BACKUP_GID: "1000"
    volumes:
      - ${MINECRAFT_DATA}:/data:ro
      - ${BACKUP_DATA}:/backups
networks: {}
