services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    # This bypasses network isolation and makes IPv6 easier (optional; see below)
    container_name: cloudflare-ddns
    restart: always
    user: "1000:1000"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=CLOUDFLARE-TOKEN
        # Your Cloudflare API token
      - DOMAINS=test.test.com
        # Your domains (separated by commas)
      - PROXIED=false
        # Tell Cloudflare to cache webpages and hide your IP (optional)
